"""Testing

Revision ID: 4914ed3aa993
Revises: 55a598bb0ac2
Create Date: 2023-07-26 15:55:24.930242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4914ed3aa993'
down_revision = '55a598bb0ac2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
