"""Create Items Table

Revision ID: 55a598bb0ac2
Revises: b9ebf1216f2e
Create Date: 2023-07-25 16:43:20.149559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a598bb0ac2'
down_revision = 'b9ebf1216f2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
