"""Testing

Revision ID: 95adcb9d95d5
Revises: 4914ed3aa993
Create Date: 2023-07-26 16:00:28.320577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95adcb9d95d5'
down_revision = '4914ed3aa993'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
