"""Update User Info

Revision ID: b9ebf1216f2e
Revises: 0428b0717f3b
Create Date: 2023-07-25 15:48:08.246692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ebf1216f2e'
down_revision = '0428b0717f3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('jwt_expiration_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'jwt_expiration_time')
    # ### end Alembic commands ###
